In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('cancer.csv')

In [3]:
x = np.array(data.loc[:,'radius']).reshape(-1,1)
y = np.array(data.loc[:,'diagnosis'])

In [4]:
x

array([[5. ],
       [4.8],
       [1. ],
       [2. ],
       [3. ],
       [3.5],
       [3.8],
       [2.5],
       [3.1],
       [3.4]])

In [4]:
xtr,xt,ytr,yt = train_test_split(x,y,test_size=0.30,random_state=123)

In [5]:
logr = LogisticRegression()
logr.fit(xtr,ytr)

LogisticRegression()

In [6]:
logr.predict(np.array(2).reshape(-1,1))

array([0], dtype=int64)

In [27]:
y

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int64)